# Version matching according to PEP-440
# run: conda env create --file environment.yml
name: shared_mobility
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytest
  - numpy
  - pandas
  - plotly
  - pymongo
  - requests
  - neovim
  - isort
  - jupyterlab
  - ipython
  - ipdb
  - python-dotenv
  - geopandas
  - geopy
  - osmnx
  - networkx
  - pyproj
  - geoalchemy2
  - sqlalchemy
  - great-expectations
  - airflow
  - apache-airflow-providers-mongo
  - apache-airflow-providers-postgres
